export const INCREMENT_ITEM_COUNT = 'INCREMENT_ITEM_COUNT';
export const SET_ITEM_COUNT = 'SET_ITEM_COUNT';
export const DECREMENT_ITEM_COUNT = 'DECREMENT_ITEM_COUNT';
export const DROP_ITEM = 'DROP_ITEM';