export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_EDITABLE_PRODUCTS = "GET_EDITABLE_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
