export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_EDITABLE_PRODUCTS = "GET_EDITABLE_PRODUCTS";
export const CLEAR_CURRENT_PRODUCTS = "CLEAR_CURRENT_PRODUCTS";
export const CLEAR_CURRENT_EDITABLE_PRODUCTS = "CLEAR_CURRENT_EDITABLE_PRODUCTS";
